services:
  redlib:
    image: ghcr.io/evrial/redlib:latest
    restart: always
    container_name: redlib
    ports:
      - 8080:8080
    user: nobody
    read_only: true
    security_opt:
      - no-new-privileges:true
      # - seccomp=seccomp-redlib.json
    env_file: .env
