name: Auto-Approve & Merge
on:
  workflow_run:
    workflows: ["Build and push Docker image"] # Name of your main Docker CI file
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.triggering_actor == 'renovate[bot]' || 
       github.event.workflow_run.triggering_actor == 'dependabot[bot]')
    steps:
      - name: Approve and Merge
        run: |
          PR_NUMBER=$(gh pr list --head "${{ github.event.workflow_run.head_branch }}" --json number --jq '.[0].number')
          gh pr review --approve "$PR_NUMBER"
          gh pr merge --auto --merge "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
